
// .cpp와 .o파일을 다룰 것임을 표기

// compile할 object파일들 설정

// compile할 테스트코드의 object파일을 포함한 object 파일들 설정

// CXX 설정

// 실행파일 이름 설정



// 실행파일 : 컴파일에 사용될 object파일들
//  (탭으로 띄운 후) 컴파일 명령어 사용


// clean은 make 결과 생성된 파일들 모두 삭제


// 컴파일하기 위해 필요한 파일들 설정
